server:
  port: 8001

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示要定义的名称用于bingding整合
          type: rabbit #消息组建类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: 39.98.222.209
                port: 5672
                username: admin
                password: gwall
                virtual-host: /
      bindings: #服务的整合处理
        output: #这个名字是一个通道的名称，用于生产者
          destination: studyExchange #表示要使用的exchange名称定义
          content-type: application/json
          binder: defaultRabbit       

eureka:
  instance:
    instance-id: payment8001
    prefer-id-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位位秒(默认30秒)
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到自后一次心跳后等待时间上线，单位位秒(默认90秒)超时将剔除服务
    lease-expiration-duration-in-seconds: 2
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    fetch-registry: true    
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要以来这个地址
      #defaultZone: http://eureka-server7001.com:7001/eureka/,http://eureka-server7002.com:7002/eureka/
      defaultZone: http://eureka-server7001.com:7001/eureka/
# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.atguigu.springcloud.entites
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*.xml
